# the value of price change 
# where we consider one grid step
price_chage_percent = 3.5

# how much percents the price should go up  
# from opened order price to close the order
# with profit
min_percent_of_profit = 3.4

# defines maximum amount (%) of currency
# we can spend on trading
trading_currency_limit_percent = 50

# how much currency will be traded per one
# grid step (grid row). 
# percent of value limited by 
# trading_currency_limit_percent
grid_step_amount_percent = 2.1