# how much the price should change before we place an order
price_chage_percentage = 5

# number of buy orders we can place before stop buying 
# and begin to wait while price will go up
orders_grid_down_levels = 4

# buy order initial amount 
buy_order_amount = 2

# how much the amount of the current order 
# is greater than the amount of the previous one
amount_level_factor = 2