# percent of price fall to 
# consider entry point detection
price_fall = 3

# how much percents the price should grow up  
# to achive minimum profit
min_percent_of_profit = 1.1

# defines maximum amount (%) of currency
# we can spend on each trade
trading_amount_percent = 10
